### ISSUE TITLE
How to update values in a specific entry?

### ISSUE THREAD

**Issue by tanmaybhatt** [abellion/ngDatabase#3]
Ofcourse, i can do it from SQL query , but is there any way so that i can update values of specific entry through update function?

**Comment by abellion** [comment]
Hi,

Of course you can, please refer to the setBy method : https://github.com/abellion/ngDatabase#standards

```
 usersRepository.setBy({'id': myId}).update({ /* ... */ })
```

**Comment by tanmaybhatt** [comment]
Ahh .. silly me , i should have tried that . Thanx !
